/// Calls a `$callback` with sizes of the arrays for which traits must be implemented
macro_rules! array_impls {
    ($callback:ident) => {
        // impls for arrays of sizes [1..32] (size = 0 is always implemented by hands)
        impls_inner!(
            1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
            20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32;
            $callback
        );

        // Some useful impls
        impls_inner!(
            40, // 8 * 5
            48, // 8 * 6
            56, // 8 * 7
            64, // 8 * 8
            72, // 8 * 9
            80, // 8 * 10
            88, // 8 * 11
            96, // 8 * 12

            100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, // 100 * n, n <- [1..10]

            128, // 2 ** 7
            256, // 2 ** 8
            512, // 2 ** 9
            1024, // 2 ** 10
            2048, // 2 ** 11
            4096, // 2 ** 12
            8192, // 2 ** 13
            16384, // 2 ** 14
            32768, // 2 ** 15
            65536 // 2 ** 16
            ;
            $callback
        );

        // impls for arrays of sizes [33..128] (except sizes that implemented by default)
        #[cfg(feature = "array-impls-33-128")]
        impls_inner!(
            33, 34, 35, 36, 37, 38, 39, /* 40, */ 41, 42, 43, 44, 45, 46, 47, /* 48, */ 49, 50, 51,
            52, 53, 54, 55, /* 56, */ 57, 58, 59, 60, 61, 62, 63, /* 64, */ 65, 66, 67, 68, 69, 70,
            71, /* 72, */ 73, 74, 75, 76, 77, 78, 79, /* 80, */ 81, 82, 83, 84, 85, 86, 87,
            /* 88, */ 89, 90, 91, 92, 93, 94, 95, /* 96, */ 97, 98, 99, /* 100, */ 101, 102, 103,
            104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
            121, 122, 123, 124, 125, 126, 127 /*, 128 */;
            $callback
        );

        // impls for arrays of sizes [129..255] (except sizes that implemented by default)
        #[cfg(feature = "array-impls-33-256")]
        impls_inner!(
            129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
            146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
            163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
            180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196,
            197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213,
            214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230,
            231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247,
            248, 249, 250, 251, 252, 253, 254, 255, 256;
            $callback
        );
    };
}

/// helper for `array_impls!`
macro_rules! impls_inner {
    ($( $size:tt ),+; $callback:ident) => {
        $(
            $callback!($size);
        )+
    };
}

macro_rules! array_init_by_f {
    (0, $f:ident) => {
        compile_error!("please init empty array properly")
    };
    // Fast path for sizes 1..32
    (1, $f:ident) => {
        [$f(0)]
    };
    (2, $f:ident) => {
        [$f(0), $f(1)]
    };
    (3, $f:ident) => {
        [$f(0), $f(1), $f(2)]
    };
    (4, $f:ident) => {
        [$f(0), $f(1), $f(2), $f(3)]
    };
    (5, $f:ident) => {
        [$f(0), $f(1), $f(2), $f(3), $f(4)]
    };
    (6, $f:ident) => {
        [$f(0), $f(1), $f(2), $f(3), $f(4), $f(5)]
    };
    (7, $f:ident) => {
        [$f(0), $f(1), $f(2), $f(3), $f(4), $f(5), $f(6)]
    };
    (8, $f:ident) => {
        [$f(0), $f(1), $f(2), $f(3), $f(4), $f(5), $f(6), $f(7)]
    };
    (9, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
        ]
    };
    (10, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
            $f(9),
        ]
    };
    (11, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
            $f(9),
            $f(10),
        ]
    };
    (12, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
            $f(9),
            $f(10),
            $f(11),
        ]
    };
    (13, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
            $f(9),
            $f(10),
            $f(11),
            $f(12),
        ]
    };
    (14, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
            $f(9),
            $f(10),
            $f(11),
            $f(12),
            $f(13),
        ]
    };
    (15, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
            $f(9),
            $f(10),
            $f(11),
            $f(12),
            $f(13),
            $f(14),
        ]
    };
    (16, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
            $f(9),
            $f(10),
            $f(11),
            $f(12),
            $f(13),
            $f(14),
            $f(15),
        ]
    };
    (17, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
            $f(9),
            $f(10),
            $f(11),
            $f(12),
            $f(13),
            $f(14),
            $f(15),
            $f(16),
        ]
    };
    (18, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
            $f(9),
            $f(10),
            $f(11),
            $f(12),
            $f(13),
            $f(14),
            $f(15),
            $f(16),
            $f(17),
        ]
    };
    (19, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
            $f(9),
            $f(10),
            $f(11),
            $f(12),
            $f(13),
            $f(14),
            $f(15),
            $f(16),
            $f(17),
            $f(18),
        ]
    };
    (20, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
            $f(9),
            $f(10),
            $f(11),
            $f(12),
            $f(13),
            $f(14),
            $f(15),
            $f(16),
            $f(17),
            $f(18),
            $f(19),
        ]
    };
    (21, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
            $f(9),
            $f(10),
            $f(11),
            $f(12),
            $f(13),
            $f(14),
            $f(15),
            $f(16),
            $f(17),
            $f(18),
            $f(19),
            $f(20),
        ]
    };
    (22, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
            $f(9),
            $f(10),
            $f(11),
            $f(12),
            $f(13),
            $f(14),
            $f(15),
            $f(16),
            $f(17),
            $f(18),
            $f(19),
            $f(20),
            $f(21),
        ]
    };
    (23, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
            $f(9),
            $f(10),
            $f(11),
            $f(12),
            $f(13),
            $f(14),
            $f(15),
            $f(16),
            $f(17),
            $f(18),
            $f(19),
            $f(20),
            $f(21),
            $f(22),
        ]
    };
    (24, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
            $f(9),
            $f(10),
            $f(11),
            $f(12),
            $f(13),
            $f(14),
            $f(15),
            $f(16),
            $f(17),
            $f(18),
            $f(19),
            $f(20),
            $f(21),
            $f(22),
            $f(23),
        ]
    };
    (25, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
            $f(9),
            $f(10),
            $f(11),
            $f(12),
            $f(13),
            $f(14),
            $f(15),
            $f(16),
            $f(17),
            $f(18),
            $f(19),
            $f(20),
            $f(21),
            $f(22),
            $f(23),
            $f(24),
        ]
    };
    (26, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
            $f(9),
            $f(10),
            $f(11),
            $f(12),
            $f(13),
            $f(14),
            $f(15),
            $f(16),
            $f(17),
            $f(18),
            $f(19),
            $f(20),
            $f(21),
            $f(22),
            $f(23),
            $f(24),
            $f(25),
        ]
    };
    (27, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
            $f(9),
            $f(10),
            $f(11),
            $f(12),
            $f(13),
            $f(14),
            $f(15),
            $f(16),
            $f(17),
            $f(18),
            $f(19),
            $f(20),
            $f(21),
            $f(22),
            $f(23),
            $f(24),
            $f(25),
            $f(26),
        ]
    };
    (28, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
            $f(9),
            $f(10),
            $f(11),
            $f(12),
            $f(13),
            $f(14),
            $f(15),
            $f(16),
            $f(17),
            $f(18),
            $f(19),
            $f(20),
            $f(21),
            $f(22),
            $f(23),
            $f(24),
            $f(25),
            $f(26),
            $f(27),
        ]
    };
    (29, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
            $f(9),
            $f(10),
            $f(11),
            $f(12),
            $f(13),
            $f(14),
            $f(15),
            $f(16),
            $f(17),
            $f(18),
            $f(19),
            $f(20),
            $f(21),
            $f(22),
            $f(23),
            $f(24),
            $f(25),
            $f(26),
            $f(27),
            $f(28),
        ]
    };
    (30, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
            $f(9),
            $f(10),
            $f(11),
            $f(12),
            $f(13),
            $f(14),
            $f(15),
            $f(16),
            $f(17),
            $f(18),
            $f(19),
            $f(20),
            $f(21),
            $f(22),
            $f(23),
            $f(24),
            $f(25),
            $f(26),
            $f(27),
            $f(28),
            $f(29),
        ]
    };
    (31, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
            $f(9),
            $f(10),
            $f(11),
            $f(12),
            $f(13),
            $f(14),
            $f(15),
            $f(16),
            $f(17),
            $f(18),
            $f(19),
            $f(20),
            $f(21),
            $f(22),
            $f(23),
            $f(24),
            $f(25),
            $f(26),
            $f(27),
            $f(28),
            $f(29),
            $f(30),
        ]
    };
    (32, $f:ident) => {
        [
            $f(0),
            $f(1),
            $f(2),
            $f(3),
            $f(4),
            $f(5),
            $f(6),
            $f(7),
            $f(8),
            $f(9),
            $f(10),
            $f(11),
            $f(12),
            $f(13),
            $f(14),
            $f(15),
            $f(16),
            $f(17),
            $f(18),
            $f(19),
            $f(20),
            $f(21),
            $f(22),
            $f(23),
            $f(24),
            $f(25),
            $f(26),
            $f(27),
            $f(28),
            $f(29),
            $f(30),
            $f(31),
        ]
    };

    ($size:literal, $f:ident) => {
        $crate::util::init::array_init_fn($f)
    };
}

macro_rules! array_init_by_try_f {
    // Fast path for sizes 1..32
    (1, $f:ident) => {
        [$f(0)?]
    };
    (2, $f:ident) => {
        [$f(0)?, $f(1)?]
    };
    (3, $f:ident) => {
        [$f(0)?, $f(1)?, $f(2)?]
    };
    (4, $f:ident) => {
        [$f(0)?, $f(1)?, $f(2)?, $f(3)?]
    };
    (5, $f:ident) => {
        [$f(0)?, $f(1)?, $f(2)?, $f(3)?, $f(4)?]
    };
    (6, $f:ident) => {
        [$f(0)?, $f(1)?, $f(2)?, $f(3)?, $f(4)?, $f(5)?]
    };
    (7, $f:ident) => {
        [$f(0)?, $f(1)?, $f(2)?, $f(3)?, $f(4)?, $f(5)?, $f(6)?]
    };
    (8, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
        ]
    };
    (9, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
        ]
    };
    (10, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
            $f(9)?,
        ]
    };
    (11, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
            $f(9)?,
            $f(10)?,
        ]
    };
    (12, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
            $f(9)?,
            $f(10)?,
            $f(11)?,
        ]
    };
    (13, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
            $f(9)?,
            $f(10)?,
            $f(11)?,
            $f(12)?,
        ]
    };
    (14, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
            $f(9)?,
            $f(10)?,
            $f(11)?,
            $f(12)?,
            $f(13)?,
        ]
    };
    (15, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
            $f(9)?,
            $f(10)?,
            $f(11)?,
            $f(12)?,
            $f(13)?,
            $f(14)?,
        ]
    };
    (16, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
            $f(9)?,
            $f(10)?,
            $f(11)?,
            $f(12)?,
            $f(13)?,
            $f(14)?,
            $f(15)?,
        ]
    };
    (17, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
            $f(9)?,
            $f(10)?,
            $f(11)?,
            $f(12)?,
            $f(13)?,
            $f(14)?,
            $f(15)?,
            $f(16)?,
        ]
    };
    (18, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
            $f(9)?,
            $f(10)?,
            $f(11)?,
            $f(12)?,
            $f(13)?,
            $f(14)?,
            $f(15)?,
            $f(16)?,
            $f(17)?,
        ]
    };
    (19, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
            $f(9)?,
            $f(10)?,
            $f(11)?,
            $f(12)?,
            $f(13)?,
            $f(14)?,
            $f(15)?,
            $f(16)?,
            $f(17)?,
            $f(18)?,
        ]
    };
    (20, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
            $f(9)?,
            $f(10)?,
            $f(11)?,
            $f(12)?,
            $f(13)?,
            $f(14)?,
            $f(15)?,
            $f(16)?,
            $f(17)?,
            $f(18)?,
            $f(19)?,
        ]
    };
    (21, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
            $f(9)?,
            $f(10)?,
            $f(11)?,
            $f(12)?,
            $f(13)?,
            $f(14)?,
            $f(15)?,
            $f(16)?,
            $f(17)?,
            $f(18)?,
            $f(19)?,
            $f(20)?,
        ]
    };
    (22, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
            $f(9)?,
            $f(10)?,
            $f(11)?,
            $f(12)?,
            $f(13)?,
            $f(14)?,
            $f(15)?,
            $f(16)?,
            $f(17)?,
            $f(18)?,
            $f(19)?,
            $f(20)?,
            $f(21)?,
        ]
    };
    (23, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
            $f(9)?,
            $f(10)?,
            $f(11)?,
            $f(12)?,
            $f(13)?,
            $f(14)?,
            $f(15)?,
            $f(16)?,
            $f(17)?,
            $f(18)?,
            $f(19)?,
            $f(20)?,
            $f(21)?,
            $f(22)?,
        ]
    };
    (24, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
            $f(9)?,
            $f(10)?,
            $f(11)?,
            $f(12)?,
            $f(13)?,
            $f(14)?,
            $f(15)?,
            $f(16)?,
            $f(17)?,
            $f(18)?,
            $f(19)?,
            $f(20)?,
            $f(21)?,
            $f(22)?,
            $f(23)?,
        ]
    };
    (25, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
            $f(9)?,
            $f(10)?,
            $f(11)?,
            $f(12)?,
            $f(13)?,
            $f(14)?,
            $f(15)?,
            $f(16)?,
            $f(17)?,
            $f(18)?,
            $f(19)?,
            $f(20)?,
            $f(21)?,
            $f(22)?,
            $f(23)?,
            $f(24)?,
        ]
    };
    (26, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
            $f(9)?,
            $f(10)?,
            $f(11)?,
            $f(12)?,
            $f(13)?,
            $f(14)?,
            $f(15)?,
            $f(16)?,
            $f(17)?,
            $f(18)?,
            $f(19)?,
            $f(20)?,
            $f(21)?,
            $f(22)?,
            $f(23)?,
            $f(24)?,
            $f(25)?,
        ]
    };
    (27, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
            $f(9)?,
            $f(10)?,
            $f(11)?,
            $f(12)?,
            $f(13)?,
            $f(14)?,
            $f(15)?,
            $f(16)?,
            $f(17)?,
            $f(18)?,
            $f(19)?,
            $f(20)?,
            $f(21)?,
            $f(22)?,
            $f(23)?,
            $f(24)?,
            $f(25)?,
            $f(26)?,
        ]
    };
    (28, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
            $f(9)?,
            $f(10)?,
            $f(11)?,
            $f(12)?,
            $f(13)?,
            $f(14)?,
            $f(15)?,
            $f(16)?,
            $f(17)?,
            $f(18)?,
            $f(19)?,
            $f(20)?,
            $f(21)?,
            $f(22)?,
            $f(23)?,
            $f(24)?,
            $f(25)?,
            $f(26)?,
            $f(27)?,
        ]
    };
    (29, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
            $f(9)?,
            $f(10)?,
            $f(11)?,
            $f(12)?,
            $f(13)?,
            $f(14)?,
            $f(15)?,
            $f(16)?,
            $f(17)?,
            $f(18)?,
            $f(19)?,
            $f(20)?,
            $f(21)?,
            $f(22)?,
            $f(23)?,
            $f(24)?,
            $f(25)?,
            $f(26)?,
            $f(27)?,
            $f(28)?,
        ]
    };
    (30, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
            $f(9)?,
            $f(10)?,
            $f(11)?,
            $f(12)?,
            $f(13)?,
            $f(14)?,
            $f(15)?,
            $f(16)?,
            $f(17)?,
            $f(18)?,
            $f(19)?,
            $f(20)?,
            $f(21)?,
            $f(22)?,
            $f(23)?,
            $f(24)?,
            $f(25)?,
            $f(26)?,
            $f(27)?,
            $f(28)?,
            $f(29)?,
        ]
    };
    (31, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
            $f(9)?,
            $f(10)?,
            $f(11)?,
            $f(12)?,
            $f(13)?,
            $f(14)?,
            $f(15)?,
            $f(16)?,
            $f(17)?,
            $f(18)?,
            $f(19)?,
            $f(20)?,
            $f(21)?,
            $f(22)?,
            $f(23)?,
            $f(24)?,
            $f(25)?,
            $f(26)?,
            $f(27)?,
            $f(28)?,
            $f(29)?,
            $f(30)?,
        ]
    };
    (32, $f:ident) => {
        [
            $f(0)?,
            $f(1)?,
            $f(2)?,
            $f(3)?,
            $f(4)?,
            $f(5)?,
            $f(6)?,
            $f(7)?,
            $f(8)?,
            $f(9)?,
            $f(10)?,
            $f(11)?,
            $f(12)?,
            $f(13)?,
            $f(14)?,
            $f(15)?,
            $f(16)?,
            $f(17)?,
            $f(18)?,
            $f(19)?,
            $f(20)?,
            $f(21)?,
            $f(22)?,
            $f(23)?,
            $f(24)?,
            $f(25)?,
            $f(26)?,
            $f(27)?,
            $f(28)?,
            $f(29)?,
            $f(30)?,
            $f(31)?,
        ]
    };

    ($size:literal, $f:ident) => {
        $crate::util::init::try_array_init_fn($f)?
    };
}

macro_rules! array_init_by_next {
    (0, $iter:ident) => {
        compile_error!("please init empty array properly")
    };
    // Fast path for sizes 1..32
    (1, $iter:ident) => {
        [$iter.next()?]
    };
    (2, $iter:ident) => {
        [$iter.next()?, $iter.next()?]
    };
    (3, $iter:ident) => {
        [$iter.next()?, $iter.next()?, $iter.next()?]
    };
    (4, $iter:ident) => {
        [$iter.next()?, $iter.next()?, $iter.next()?, $iter.next()?]
    };
    (5, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (6, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (7, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (8, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (9, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (10, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (11, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (12, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (13, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (14, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (15, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (16, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (17, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (18, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (19, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (20, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (21, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (22, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (23, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (24, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (25, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (26, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (27, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (28, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (29, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (30, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (31, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };
    (32, $iter:ident) => {
        [
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
            $iter.next()?,
        ]
    };

    ($size:literal, $iter:ident) => {
        $crate::util::init::array_init_iter($iter)?
    };
}
